language: ruby
rvm:
  - 2.0.0
branches:
  only:
    - master
    - develop
bundler_args: --without development --path vendor/bundle
script: "bundle exec rake db:migrate spec"
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: KF3NLGLR6d7X7cSU5N7zGoOZWbV7VMByz8cqm918VvWo1biQ4moOk1NeCk1Fbic57pXbh4YOJxEpYLxYEAUNS9p6yPVivD44pA5zizetre4egkvkmZsxczMN5HiDWRo0GpwdZazdFnXIwKtKrl6tdpPnSxSrU6eOxd3xGiJbzKU=
  app: suicat
  on:
    repo: sinsoku/suicat
    branch: develop
  run:
    - "rake db:migrate"
    - restart
